"""Generate the table of live ids in docs/tables/ID-MAP.md. Case P18.

The table used to be kept by hand and drifted twice: ids that had been renamed
stayed listed, new families were never added, and nothing noticed because no
check read the file. Now every row is counted from where the id is actually
defined -- a requirement row in a module document, a case row, a static check
row, a checklist row, a decision heading, a ticket file -- and written between
the two markers below. What a family *means* is the one thing still written
here by hand, in FAMILIES; it changes far less often than the ranges do.

Usage:
    python tools/gen_id_map.py --check    exit 1 if the table is out of date (selfcheck)
    python tools/gen_id_map.py --write    rewrite the table in place

Exit 0 = up to date (or rewritten), 1 = out of date, 2 = the markers are missing.
"""

import argparse
import glob
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ID_MAP = os.path.join(ROOT, "docs", "tables", "ID-MAP.md")
BEGIN = "<!-- BEGIN generated by tools/gen_id_map.py -- do not edit by hand -->"
END = "<!-- END generated -->"

# (family, what it is, files to scan, pattern whose group 1 is the id)
ROW = r"^\|\s*(?:\*\*|`)?(%s)(?:\*\*|`)?\s*\|"
FAMILIES = [
    ("R", "需求（一句可判定的话）", ["docs/modules/M*.md"], ROW % r"R\d-\d{2}"),
    ("T", "测试用例", ["docs/modules/M*.md", "docs/modules/M*/*.md",
                    "docs/engineering/HOW-TO-RUN-TESTS.md",
                    "docs/tables/ACCEPTANCE-CHECKLIST.md"],
     r"(?:" + (ROW % r"T\d-\d{2}[a-z]?") + r")|(?:^##\s+(T\d-\d{2}[a-z]?)\s+·)"),
    ("P", "静态检查（不碰硬件，看源码和文档）", ["docs/engineering/HOW-TO-RUN-TESTS.md"],
     ROW % r"P\d+"),
    ("CHK", "验收单的一项（A 改动后自检 / B 发版 / C 单板出厂）",
     ["docs/tables/ACCEPTANCE-CHECKLIST.md"], ROW % r"CHK-[A-C]\d+"),
    ("D", "决议（定了就不重开，除非出现它写明的重开条件）",
     ["docs/tables/DECISIONS.md"], r"^##\s+(\d+)\s+·"),
]
TICKET_FILE = re.compile(r"^([A-Z][A-Z0-9]*)-(\d+)-")


def relink(path):
    return os.path.relpath(path, os.path.dirname(ID_MAP)).replace(os.sep, "/")


def split_id(i):
    """Sort key and grouping prefix: R1-07 -> ('R1-', 7, '')."""
    m = re.match(r"^(.*?)(\d+)([a-z]?)$", i)
    return m.group(1), int(m.group(2)), m.group(3)


def ranges(ids):
    """Compress sorted ids into runs: `R1-01`–`R1-05` `R1-07`."""
    items = sorted(set(ids), key=lambda i: split_id(i))
    runs, start, prev = [], None, None
    for i in items:
        p, n, s = split_id(i)
        if prev is not None:
            pp, pn, ps = split_id(prev)
            nxt = (p == pp and ((not s and not ps and n == pn + 1) or
                                (s and ps and n == pn and ord(s) == ord(ps) + 1) or
                                (s == "a" and not ps and n == pn)))
            if not nxt:
                runs.append((start, prev))
                start = i
        else:
            start = i
        prev = i
    if start is not None:
        runs.append((start, prev))
    return " ".join("`%s`" % a if a == b else "`%s`–`%s`" % (a, b) for a, b in runs)


def read(path):
    return io.open(path, encoding="utf-8").read()


def scan(globs, pattern):
    """id -> set of files that define it, skipping fenced code."""
    rx = re.compile(pattern)
    found = {}
    for g in globs:
        for path in sorted(glob.glob(os.path.join(ROOT, g))):
            if os.path.abspath(path) == ID_MAP:
                continue
            fenced = False
            for line in read(path).splitlines():
                if line.lstrip().startswith(("```", "~~~")):
                    fenced = not fenced
                    continue
                m = None if fenced else rx.match(line)
                if m:
                    i = next(x for x in m.groups() if x)
                    found.setdefault(i, set()).add(path)
    return found


def rows():
    out = []
    for fam, what, globs, pattern in FAMILIES:
        found = scan(globs, pattern)
        groups = {}
        for i in found:
            key = split_id(i)[0] if fam in ("R", "T", "CHK") else fam
            groups.setdefault(key, []).append(i)
        for key in sorted(groups):
            ids = groups[key]
            files = sorted({f for i in ids for f in found[i]})
            where = "、".join("[%s](%s)" % (os.path.basename(f), relink(f)) for f in files)
            shown = ranges(ids) if fam != "D" else "第 %s 条" % ranges(ids).replace("`", "")
            out.append((shown, what, len(ids), where))
    tickets = {}
    for path in sorted(glob.glob(os.path.join(ROOT, "maps", "*", "issues", "*.md"))):
        m = TICKET_FILE.match(os.path.basename(path))
        if m:
            tickets.setdefault((m.group(1), os.path.dirname(os.path.dirname(path))), []).append(m.group(1) + "-" + m.group(2))
    for (prefix, mapdir), ids in sorted(tickets.items()):
        mapfile = os.path.join(mapdir, "map.md")
        title = read(mapfile).splitlines()[0].lstrip("# ").strip() if os.path.exists(mapfile) else ""
        out.append((ranges(ids), "wayfinder 的票，属于「%s」" % title, len(ids),
                    "[%s/issues/](%s)" % (os.path.basename(mapdir), relink(os.path.join(mapdir, "issues")))))
    return out


def table():
    lines = [BEGIN, "", "| 编号 | 是什么 | 条数 | 定义在哪 |", "|---|---|---|---|"]
    lines += ["| %s | %s | %d | %s |" % r for r in rows()]
    lines += ["", END]
    return lines


def main():
    ap = argparse.ArgumentParser()
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = ap.parse_args()

    text = read(ID_MAP)
    nl = "\r\n" if "\r\n" in text else "\n"
    if BEGIN not in text or END not in text:
        print("ID-MAP.md has no generated-table markers; add them where the table belongs")
        return 2
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = head + nl.join(table()) + tail
    if new == text:
        print("ID-MAP.md: the live-id table is up to date")
        return 0
    if args.write:
        io.open(ID_MAP, "w", encoding="utf-8", newline="").write(new)
        print("ID-MAP.md: live-id table rewritten")
        return 0
    print("ID-MAP.md: the live-id table is out of date -- run: python tools/gen_id_map.py --write")
    return 1


if __name__ == "__main__":
    sys.exit(main())
